[versions]
velocity-api = "3.5.0-SNAPSHOT"
floodgate-api = "2.2.5-SNAPSHOT"
resource-factory = "1.3.1"
run-velocity = "3.0.2"

[libraries]
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity-api" }
floodgate-api = { module = "org.geysermc.floodgate:api", version.ref = "floodgate-api" }

[plugins]
velocity-resource-factory = { id = "xyz.jpenilla.resource-factory-velocity-convention", version.ref = "resource-factory" }
run-velocity = { id = "xyz.jpenilla.run-velocity", version.ref = "run-velocity" }